language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

install: 
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  - phpenv rehash

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  - drush make build-motionsplan.make ../motionsplan-dev.dk
  - cd ../motionsplan-dev.dk
  - sudo chmod -R 777 sites/
  - drush si motionsplan_dk --verbose --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="motionsplan.dk" --yes
  - drush en motionsplan_deploy -y
  - drush cc all --yes

script: 

  - test -d sites/all/modules/contrib

  # Test if any features are overridden.
  - profiles/motionsplan_dk/scripts/check-overridden.sh
