language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make build-motionsplan.make ../motionsplan-dev.dk
  - cd ../motionsplan-dev.dk
  - sudo chmod -R 777 sites/
  - drush si motionsplan_dk --verbose --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="motionsplan.dk" --yes
  - drush cc all --yes

script: 
  - test -d sites/all/modules/contrib

